# Generated by Django 4.2.6 on 2023-10-30 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('phone_number', models.IntegerField(null=True)),
                ('city', models.CharField(max_length=15)),
                ('station', models.CharField(max_length=30)),
                ('ans1', models.CharField(max_length=3, null=True)),
                ('ans2', models.CharField(max_length=3, null=True)),
                ('ans3', models.SmallIntegerField(null=True)),
                ('ans4', models.CharField(max_length=3, null=True)),
                ('ans5', models.SmallIntegerField()),
                ('textbox', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
