# Generated by Django 4.2.6 on 2023-11-03 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0003_trial_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='trial_model2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('police_station', models.CharField(max_length=50)),
            ],
        ),
    ]
