# Generated by Django 4.2.6 on 2023-11-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0004_trial_model2'),
    ]

    operations = [
        migrations.CreateModel(
            name='compliment_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('compliment', models.TextField()),
            ],
        ),
    ]
