# Generated by Django 4.2.6 on 2023-11-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0005_compliment_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='suggestion_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=50, null=True)),
                ('suggestion', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='compliment_model',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='compliment_model',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='compliment_model',
            name='phone_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
