# Generated by Django 4.2.6 on 2023-11-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0006_suggestion_model_alter_compliment_model_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='incident_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=50)),
                ('location', models.TextField()),
                ('incident_with', models.CharField(max_length=50)),
                ('incident', models.TextField()),
            ],
        ),
    ]
