# Generated by Django 4.2.6 on 2023-11-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0007_incident_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident_model',
            name='incident_with',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
