# Generated by Django 4.2.6 on 2023-11-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0008_alter_incident_model_incident_with'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50)),
                ('police_station', models.CharField(max_length=50)),
                ('answer1', models.CharField(max_length=10, null=True)),
                ('answer2', models.CharField(max_length=10, null=True)),
                ('rating1', models.IntegerField(null=True)),
                ('answer4', models.CharField(max_length=10, null=True)),
                ('answer5', models.CharField(max_length=10, null=True)),
                ('rating2', models.IntegerField(null=True)),
                ('rating3', models.IntegerField(null=True)),
                ('rating4', models.IntegerField(null=True)),
                ('rating5', models.IntegerField(null=True)),
                ('rating6', models.IntegerField(null=True)),
                ('overall_rating', models.IntegerField()),
                ('written_feedback', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='signup_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('police_station', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
