# Generated by Django 4.2.6 on 2023-11-03 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0009_feedback_model_signup_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback_model',
            old_name='rating1',
            new_name='answer10',
        ),
        migrations.RenameField(
            model_name='feedback_model',
            old_name='rating2',
            new_name='answer3',
        ),
        migrations.RenameField(
            model_name='feedback_model',
            old_name='rating3',
            new_name='answer6',
        ),
        migrations.RenameField(
            model_name='feedback_model',
            old_name='rating4',
            new_name='answer7',
        ),
        migrations.RenameField(
            model_name='feedback_model',
            old_name='rating5',
            new_name='answer8',
        ),
        migrations.RenameField(
            model_name='feedback_model',
            old_name='rating6',
            new_name='answer9',
        ),
    ]
