# Generated by Django 4.2.6 on 2023-11-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0010_rename_rating1_feedback_model_answer10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback_model',
            name='overall_rating',
            field=models.IntegerField(null=True),
        ),
    ]
