# Generated by Django 4.2.6 on 2023-11-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0012_alter_feedback_model_answer10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup_model',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
