# Generated by Django 4.2.7 on 2023-11-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='compliment_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=50, null=True)),
                ('compliment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='feedback_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50)),
                ('police_station', models.CharField(max_length=50)),
                ('answer1', models.CharField(max_length=10, null=True)),
                ('answer2', models.CharField(max_length=10, null=True)),
                ('answer3', models.CharField(max_length=10, null=True)),
                ('answer4', models.CharField(max_length=10, null=True)),
                ('answer5', models.CharField(max_length=10, null=True)),
                ('answer6', models.CharField(max_length=10, null=True)),
                ('answer7', models.CharField(max_length=10, null=True)),
                ('answer8', models.CharField(max_length=10, null=True)),
                ('answer9', models.CharField(max_length=10, null=True)),
                ('answer10', models.CharField(max_length=10, null=True)),
                ('overall_rating', models.CharField(max_length=10, null=True)),
                ('written_feedback', models.TextField(null=True)),
                ('positive_or_negative', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='incident_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=50)),
                ('location', models.TextField()),
                ('incident_with', models.CharField(max_length=50, null=True)),
                ('incident', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='signup_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50, null=True)),
                ('police_station', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='suggestion_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=50, null=True)),
                ('suggestion', models.TextField()),
            ],
        ),
    ]
